### ISSUE TITLE
Incorrect candle data & SQL record duplication on insert

### ISSUE THREAD

**Issue by victorarthur** [stockmlbot/TraderCore#1]
Despite the errors, trading advice is being generated.

**Error messages**

`error: Strategy error Cannot read property 'low' of undefined {"stack":"TypeError: Cannot read property 'low' of undefined\n    at Strategy.update (/root/stockml/TraderCore/src/strategies/bb_pure/index.js:41:20)\n    at Emulator.update (/root/stockml/TraderCore/src/emulator/emulator.js:72:29)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}`

`error: SQL errorDuplicate entry '142-BCH/USDT-1566206580000' for key 'strategy_guid' {"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '142-BCH/USDT-1566206580000' for key 'strategy_guid'","stack":"Error: Duplicate entry '142-BCH/USDT-1566206580000' for key 'strategy_guid'\n    at PromisePool.query (/root/stockml/TraderCore/node_modules/mysql2/promise.js:322:22)\n    at LiveEmulator.save_advice (/root/stockml/TraderCore/src/emulator/live_emulator.js:168:18)\n    at LiveEmulator.single_update (/root/stockml/TraderCore/src/emulator/live_emulator.js:128:16)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
error: Strategy error Cannot read property 'low' of undefined {"stack":"TypeError: Cannot read property 'low' of undefined\n    at Strategy.update (/root/stockml/TraderCore/src/strategies/bb_pure/index.js:41:20)\n    at Emulator.update (/root/stockml/TraderCore/src/emulator/emulator.js:72:29)\n    at LiveEmulator.single_update (/root/stockml/TraderCore/src/emulator/live_emulator.js:114:63)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}`

**Strat settings**

![Screenshot 2019-08-19 11 23 59](https://user-images.githubusercontent.com/3355074/63254590-4ae49500-c274-11e9-856b-85b8fe8a09ec.jpg)

![Screenshot 2019-08-19 11 23 38](https://user-images.githubusercontent.com/3355074/63254625-589a1a80-c274-11e9-8472-62c7c83adddf.jpg)

**Comment by valamidev** [comment]
Should be fine from now.
